{
    "name": "Odoo Whatsapp",
    "version": "16.0.1.0.0",
    "author": "Heliconia Solutions Pvt. Ltd.",
    "summary": "whatsapp",
    "sequence": 10,
    "depends": [
        "sale",
        "account",
        "purchase",
        "phone_validation",
        "mail_gateway_whatsapp",
    ],
    "data": [
        "security/ir.model.access.csv",
        "data/sale_order_data.xml",
        "data/purchase_order_data.xml",
        "data/account_move_data.xml",
        "views/sale_order_views.xml",
        "views/mail_template_views.xml",
        "views/error.xml",
        "views/account_move_views.xml",
        "views/mail_message_views.xml",
        "views/res_config_settings_views.xml",
        "views/purchase_order_views.xml",
        "views/wahtsapp_view.xml",
        "views/whatsapp_menu.xml",
        "wizard/send_whatsapp_message_views.xml",
    ],
    "installable": True,
    "application": True,
    "external_dependencies": {
        "python": ["phonenumbers", "html2text"],
    },
    "license": "LGPL-3",
}
